version: '3.8'

services:
  mysql:
    image: mysql:8.1
    ports:
      - "3306:3306"
    expose:
      - '3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=flyway
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=example

  flyway:
    image: redgate/flyway
    depends_on: ["mysql"]
    command: migrate
    volumes: 
    - C:\Users\Hello\Desktop\Modern-DevOps-Practices\flyway\db:/flyway/db
    - C:\Users\Hello\Desktop\Modern-DevOps-Practices\flyway\migrations:/flyway/sql
    - C:\Users\Hello\Desktop\Modern-DevOps-Practices\flyway\config:/flyway/conf
